image: atlassian/default-image:2

pipelines:
  default:
    - step:
        deployment: production
        script:
          - pipe: atlassian/aws-s3-deploy:0.3.7
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: 'eu-north-1'
              S3_BUCKET: 'ozu-store-3s'
              EXPIRES: '2021-12-12'
              LOCAL_PATH: './'
              ACL: 'public-read'
