image: python:3.8.9

pipelines:
  branches:
    deployment:
    - step:
        name: Build
        script:
          - cp -a ./src/. .
          - ls
          - cd core
          - ls
          - cd ..
          - ls
          - cd ecommerce_api
          - ls
          - cd ..
          - cd src
          - ls
          - cd ..
          - git archive --format=tar.gz deployment -o ecommer_api.tar.gz
        artifacts:
          - ecommer_api.tar.gz
