image: atlassian/default-image:2

pipelines:
  branches:
    deployment-aws:
      - step:
          name: Build and Push to DockerHub
          script:
            - IMAGE_NAME=yilmazdoga/ozu-ecommerce
            - VERSION="0.1.${BITBUCKET_BUILD_NUMBER}"
            - docker build . --file Dockerfile --tag ${IMAGE_NAME}:${VERSION}
            - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
            - docker tag ${IMAGE_NAME}:${VERSION} ${IMAGE_NAME}:latest
            - docker push ${IMAGE_NAME}:latest
          services:
            - docker
          caches:
            - docker
      - step:
          name: Deploy to AWS EB
          script:
            - pipe: atlassian/aws-elasticbeanstalk-deploy:0.2.3
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: 'eu-north-1'
                APPLICATION_NAME: 'ozu-store-api'
                COMMAND: 'deploy-only'
                VERSION_LABEL: 'ozu-store-api-source-1'
                ENVIRONMENT_NAME: 'Ozustoreapi-env'
                ZIP_FILE: 'Dockerrun.aws.json'
                WAIT: 'true'