image: python:3.8.9

pipelines:
  branches:
    deployment:
    - step:
        name: Build
        script:
          - git archive --format=tar.gz deployment -o ecommer_api.tar.gz
        artifacts:
          - ecommer_api.tar.gz

    - step:
        name: Deploy to production
        deployment: production
        caches:
          - pip
        script:
          - pipe: atlassian/heroku-deploy:1.2.1
            variables:
              HEROKU_API_KEY: $HEROKU_API_KEY
              HEROKU_APP_NAME: $HEROKU_APP_NAME
              ZIP_FILE: ecommer_api.tar.gz