# Template docker-push

# This template allows you to build and push your docker image to a Docker Hub account.
# The workflow allows running tests, code linting and security scans on feature branches (as well as master).
# The docker image will be validated and pushed to the docker registry after the code is merged to master.

# Prerequisites: $DOCKERHUB_USERNAME, $DOCKERHUB_PASSWORD setup as deployment variables

image: atlassian/default-image:2

pipelines:
  branches:
    deployment:
      - step:
          name: Build and Push to DockerHub
          script:
            - IMAGE_NAME=yilmazdoga/ozu-ecommerce
            - VERSION="0.1.${BITBUCKET_BUILD_NUMBER}"
            - docker build . --file Dockerfile --tag ${IMAGE_NAME}:${VERSION}
            - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
            - docker tag ${IMAGE_NAME}:${VERSION} ${IMAGE_NAME}:latest
            - docker push ${IMAGE_NAME}:${VERSION}
          services:
            - docker
          caches:
            - docker